# Generated by Django 6.0.5 on 2026-06-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_session_key'),
        ('courses', '0003_course_duration_course_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
