# Generated by Django 6.0.5 on 2026-06-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_institution_user_role_batch_user_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('INSTITUTION_ADMIN', 'Institution Admin'), ('INSTRUCTOR', 'Instructor'), ('QUESTION_ADMIN', 'Question Paper Admin'), ('COURSE_ADMIN', 'Course & Subject Admin'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
