# Generated by Django 6.0.5 on 2026-06-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_seed_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_credits',
            field=models.IntegerField(default=100),
        ),
    ]
