# Generated by Django 6.0.5 on 2026-05-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='qubook.helpline@gmail.com', max_length=254),
        ),
    ]
