version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: qubook_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=qubook_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_db_password
    ports:
      - "127.0.0.1:5435:5432"

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qubook_backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend/media:/app/media
      - ./backend/static:/app/static
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./backend/.env

volumes:
  postgres_data:

