# Generated by Django 6.0.5 on 2026-06-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_level_options_alter_subtopic_options_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('ATTEMPT_WISE', 'Attempt Wise')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='level_name',
            field=models.CharField(blank=True, choices=[('FOUNDATION', 'Foundation'), ('INTERMEDIATE', 'Intermediate'), ('FINAL', 'Final')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='scope',
            field=models.CharField(blank=True, choices=[('PAPER_WISE', 'Paper Wise'), ('GROUP_WISE', 'Group Wise')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='calendar_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='exam_attempt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.level'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
