# Generated by Django 6.0.5 on 2026-06-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_coupon_subscriptionplan_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='restricted_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
