# Generated by Django 6.0.5 on 2026-06-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_payment_base_amount_payment_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='free_questions_per_chapter',
            field=models.IntegerField(default=3, help_text='Number of questions visible per chapter. Set -1 for unlimited (premium), 0 for no access.'),
        ),
    ]
