# Generated by Django 6.0.5 on 2026-06-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_duration_course_is_archived_and_more'),
        ('subscriptions', '0008_platformsetting_coupon_restricted_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='category_specific',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='courses.category'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='level_specific',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='courses.level'),
        ),
    ]
