# Generated by Django 6.0.5 on 2026-06-18 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_payment_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EXTEND', 'Extended'), ('SUSPEND', 'Suspended'), ('ACTIVATE', 'Activated'), ('REFUND', 'Refunded'), ('CANCEL', 'Cancelled'), ('CREATE', 'Created')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('old_end_date', models.DateTimeField(blank=True, null=True)),
                ('new_end_date', models.DateTimeField(blank=True, null=True)),
                ('old_status', models.BooleanField(blank=True, null=True)),
                ('new_status', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='subscriptions.payment')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='subscriptions.usersubscription')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
