# Generated by Django 6.0.5 on 2026-06-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscriptionauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_assistant_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='download_permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='live_class_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='mock_test_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='notes_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='question_bank_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='video_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('ONE_TIME', 'One Time Payment'), ('MONTHLY', 'Monthly Subscription'), ('QUARTERLY', 'Quarterly Subscription'), ('HALF_YEARLY', 'Half-Yearly Subscription'), ('ANNUAL', 'Annual Subscription'), ('LIFETIME', 'Lifetime Access')], max_length=20, null=True),
        ),
    ]
