# Generated by Django 6.0.5 on 2026-06-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_subscriptionplan_ai_assistant_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('ONE_TIME', 'One Time Payment'), ('MONTHLY', 'Monthly Subscription'), ('QUARTERLY', 'Quarterly Subscription'), ('HALF_YEARLY', 'Half-Yearly Subscription'), ('ANNUAL', 'Annual Subscription'), ('LIFETIME', 'Lifetime Access'), ('ATTEMPT_WISE', 'Attempt Wise')], max_length=20, null=True),
        ),
    ]
