# Generated by Django 6.0.5 on 2026-06-19 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_subscriptionplan_billing_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('QUESTIONS', 'Questions Only'), ('FULL_COURSE', 'Full Course')], default='FULL_COURSE', max_length=20),
        ),
        migrations.CreateModel(
            name='UserViewedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'paper_id')},
            },
        ),
    ]
