# Generated by Django 6.0.5 on 2026-06-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_payment_order_id_subscriptionplan_fixed_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='If True, this plan will be automatically assigned to new users on signup.'),
        ),
    ]
