# Generated by Django 6.0.5 on 2026-05-25 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CALevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CA Level',
                'verbose_name_plural': 'CA Levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ICAIPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='master_data.calevel')),
            ],
            options={
                'verbose_name': 'ICAI Paper',
                'verbose_name_plural': 'ICAI Papers',
                'ordering': ['order', 'name'],
                'unique_together': {('level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ICAIChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='master_data.icaipaper')),
            ],
            options={
                'verbose_name': 'ICAI Chapter',
                'verbose_name_plural': 'ICAI Chapters',
                'ordering': ['order', 'name'],
                'unique_together': {('paper', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ICAITopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='master_data.icaichapter')),
            ],
            options={
                'verbose_name': 'ICAI Topic',
                'verbose_name_plural': 'ICAI Topics',
                'ordering': ['order', 'name'],
                'unique_together': {('chapter', 'name')},
            },
        ),
    ]
