# Generated by Django 6.0.5 on 2026-06-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevel',
            name='qualification',
            field=models.CharField(db_index=True, default='CA', max_length=50),
        ),
    ]
