# Generated by Django 6.0.5 on 2026-06-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_calevel_qualification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calevel',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Course Level', 'verbose_name_plural': 'Course Levels'},
        ),
        migrations.AlterModelOptions(
            name='icaichapter',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Exam Chapter', 'verbose_name_plural': 'Exam Chapters'},
        ),
        migrations.AlterModelOptions(
            name='icaipaper',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Exam Paper', 'verbose_name_plural': 'Exam Papers'},
        ),
        migrations.AlterModelOptions(
            name='icaitopic',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Exam Topic', 'verbose_name_plural': 'Exam Topics'},
        ),
    ]
