# Generated by Django 6.0.5 on 2026-06-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_level_options_alter_subtopic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='validity_days',
            field=models.IntegerField(default=365),
        ),
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
