# Generated by Django 6.0.5 on 2026-06-17 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_institution_user_role_batch_user_institution'),
        ('courses', '0003_course_duration_course_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='authentication.institution'),
        ),
    ]
