# Generated by Django 6.0.5 on 2026-06-17 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='level',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpgradePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_type', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('button_text', models.CharField(default='Pay & Upgrade', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('current_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_paths', to='courses.level')),
                ('next_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_paths', to='courses.level')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField(default=0)),
                ('attendance_requirement', models.IntegerField(default=0)),
                ('mock_test_completion', models.BooleanField(default=False)),
                ('assignment_completion', models.BooleanField(default=False)),
                ('manual_approval_required', models.BooleanField(default=False)),
                ('upgrade_path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rule', to='courses.upgradepath')),
            ],
        ),
        migrations.CreateModel(
            name='UpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FORCED', 'Forced'), ('REVERTED', 'Reverted')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_upgrades', to=settings.AUTH_USER_MODEL)),
                ('upgrade_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.upgradepath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage', models.IntegerField(default=0)),
                ('progress_data', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
