# Generated by Django 6.0.5 on 2026-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_notificationtemplate_category_icon_category_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20),
        ),
    ]
