# Generated by Django 6.0.5 on 2026-06-26 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('chapter', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('goal', models.CharField(choices=[('NOTES', 'Read Notes'), ('VIDEO', 'Watch Video'), ('MCQ', 'Solve MCQs'), ('REVISION', 'Revision'), ('MOCK', 'Mock Test')], default='NOTES', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('active_duration_seconds', models.IntegerField(default=0)),
                ('questions_solved', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('pages_read', models.IntegerField(default=0)),
                ('videos_watched', models.IntegerField(default=0)),
                ('flashcards_reviewed', models.IntegerField(default=0)),
                ('learning_score', models.IntegerField(default=0)),
                ('weak_topics', models.JSONField(blank=True, default=list)),
                ('ai_coach_insight', models.TextField(blank=True, default='')),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('chapter', models.CharField(blank=True, max_length=200)),
                ('due_date', models.DateField()),
                ('interval_stage', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_revisions', to=settings.AUTH_USER_MODEL)),
                ('study_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='gamification.studysession')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('study_hours_target', models.FloatField(default=2.0)),
                ('study_hours_completed', models.FloatField(default=0.0)),
                ('mcqs_target', models.IntegerField(default=50)),
                ('mcqs_completed', models.IntegerField(default=0)),
                ('revision_target', models.IntegerField(default=1)),
                ('revision_completed', models.IntegerField(default=0)),
                ('mock_test_target', models.IntegerField(default=0)),
                ('mock_test_completed', models.IntegerField(default=0)),
                ('weak_areas_reviewed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('points_rewarded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
