# Generated by Django 6.0.5 on 2026-06-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_studysession_adaptiverevision_dailymission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailymission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailymission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdaptiveRevision',
        ),
        migrations.DeleteModel(
            name='DailyMission',
        ),
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
