# Generated by Django 6.0.5 on 2026-06-26 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_studentprogress_status'),
        ('gamification', '0004_alter_dailymission_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=200, null=True)),
                ('topic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('study_goal', models.TextField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('POMODORO', 'Pomodoro'), ('DEEP_FOCUS', 'Deep Focus'), ('STOPWATCH', 'Stopwatch'), ('COUNTDOWN', 'Countdown'), ('CUSTOM', 'Custom')], default='STOPWATCH', max_length=20)),
                ('target_duration', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('xp_earned', models.IntegerField(default=0)),
                ('coins_earned', models.IntegerField(default=0)),
                ('focus_percentage', models.FloatField(default=100.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('last_paused_at', models.DateTimeField(blank=True, null=True)),
                ('total_paused_duration', models.IntegerField(default=0)),
                ('auto_saved_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='courses.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='courses.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='gamification.studysession')),
            ],
            options={
                'db_table': 'session_breaks',
            },
        ),
        migrations.CreateModel(
            name='TimerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoro_work_duration', models.IntegerField(default=1500)),
                ('pomodoro_break_duration', models.IntegerField(default=300)),
                ('short_break_duration', models.IntegerField(default=300)),
                ('long_break_duration', models.IntegerField(default=900)),
                ('auto_start_breaks', models.BooleanField(default=False)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('sound_type', models.CharField(default='bell', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timer_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timer_settings',
            },
        ),
    ]
