"""
Complete ICAI CA master structure — Levels → Papers → Chapters.
Topics are seeded per chapter in the management command (Theory, Practical, Exam Focus).
"""

DEFAULT_TOPICS = ['Theory & Concepts', 'Practical Problems', 'Exam Focus Questions']

ICAI_MASTER = [
    {
        'name': 'CA FOUNDATION',
        'order': 1,
        'papers': [
            {
                'name': 'Paper 1 - Accounting',
                'code': 'P1',
                'order': 1,
                'chapters': [
                    'Theoretical Framework',
                    'Accounting Process',
                    'Bank Reconciliation Statement',
                    'Inventories',
                    'Depreciation and Amortisation',
                    'Bill of Exchange and Promissory Notes',
                    'Preparation of Final Accounts of Sole Proprietors',
                    'Financial Statements of Not-for-Profit Organisations',
                    'Accounts for Incomplete Records',
                    'Partnership and LLP Accounts',
                    'Company Accounts',
                ],
            },
            {
                'name': 'Paper 2 - Business Laws',
                'code': 'P2',
                'order': 2,
                'chapters': [
                    'Indian Regulatory Framework',
                    'The Indian Contract Act 1872',
                    'The Sale of Goods Act 1930',
                    'The Indian Partnership Act 1932',
                    'The Limited Liability Partnership Act 2008',
                    'The Companies Act 2013',
                    'The Negotiable Instruments Act 1881',
                ],
            },
            {
                'name': 'Paper 3 - Quantitative Aptitude',
                'code': 'P3',
                'order': 3,
                'chapters': [
                    'Ratio and Proportion, Indices, Logarithms',
                    'Equations',
                    'Linear Inequalities',
                    'Mathematics of Finance',
                    'Basic Concepts of Permutations and Combinations',
                    'Sequence and Series',
                    'Sets, Relations and Functions',
                    'Limits and Continuity Functions',
                    'Differential and Integral Calculus',
                    'Number Series',
                    'Coding and Decoding',
                    'Odd Man Out',
                    'Direction Sense Test',
                    'Seating Arrangements',
                    'Blood Relations',
                    'Statistical Description of Data',
                    'Measures of Central Tendency',
                    'Probability',
                    'Theoretical Distributions',
                    'Correlation and Regression',
                    'Index Numbers',
                ],
            },
            {
                'name': 'Paper 4 - Economics',
                'code': 'P4',
                'order': 4,
                'chapters': [
                    'Nature and Scope of Business Economics',
                    'Theory of Demand and Supply',
                    'Theory of Production and Cost',
                    'Price Determination in Different Markets',
                    'Business Cycles',
                    'Determination of National Income',
                    'Public Finance',
                    'Money Market',
                ],
            },
        ],
    },
    {
        'name': 'CA INTERMEDIATE',
        'order': 2,
        'papers': [
            {
                'name': 'Paper 1 - Advanced Accounting',
                'code': 'P1',
                'order': 1,
                'chapters': [
                    'AS 1 to AS 29',
                    'Financial Statements of Companies',
                    'Buyback of Securities',
                    'Amalgamation of Companies',
                    'Accounting for Reconstruction',
                    'Branch Accounting',
                    'Applicability of Accounting Standards',
                    'Introduction to Accounting Standards',
                ],
            },
            {
                'name': 'Paper 2 - Corporate and Other Laws',
                'code': 'P2',
                'order': 2,
                'chapters': [
                    'Preliminary',
                    'Incorporation of Company',
                    'Prospectus and Allotment',
                    'Share Capital and Debentures',
                    'Acceptance of Deposits',
                    'Registration of Charges',
                    'Management and Administration',
                    'Declaration and Payment of Dividend',
                    'Accounts of Companies',
                    'Audit and Auditors',
                    'Companies Incorporated Outside India',
                    'LLP Act 2008',
                    'General Clauses Act',
                    'Interpretation of Statutes',
                    'FEMA 1999',
                ],
            },
            {
                'name': 'Paper 3A - Direct Tax',
                'code': 'P3A',
                'order': 3,
                'chapters': [
                    'Basic Concepts',
                    'Residence and Scope of Total Income',
                    'Salaries',
                    'Income from House Property',
                    'Profits and Gains of Business and Profession',
                    'Capital Gains',
                    'Income from Other Sources',
                    'Aggregation of Income',
                    'Deductions from Gross Total Income',
                    'Advance Tax',
                    'Income Tax Liability Computation',
                ],
            },
            {
                'name': 'Paper 3B - Goods and Service Tax',
                'code': 'P3B',
                'order': 4,
                'chapters': [
                    'GST in India',
                    'Supply under GST',
                    'Charge of GST',
                    'Place of Supply',
                    'Exemptions from GST',
                    'Time of Supply',
                    'Value of Supply',
                    'Input Tax Credit',
                    'Registration',
                    'Tax Invoice',
                    'Accounts and Records',
                    'E-way Bill',
                    'Payment of Tax',
                    'TDS and TCS',
                    'Returns',
                ],
            },
            {
                'name': 'Paper 4 - Cost and Management Accounting',
                'code': 'P4',
                'order': 5,
                'chapters': [
                    'Introduction to Cost and Management Accounting',
                    'Material Cost',
                    'Employee Cost',
                    'Overheads',
                    'Activity Based Costing',
                    'Cost Sheet',
                    'Cost Accounting System',
                    'Unit and Batch Costing',
                    'Job Costing',
                    'Process Costing',
                    'Joint Products',
                    'Service Costing',
                    'Standard Costing',
                    'Marginal Costing',
                    'Budgetary Control',
                ],
            },
            {
                'name': 'Paper 5 - Auditing and Ethics',
                'code': 'P5',
                'order': 6,
                'chapters': [
                    'Nature and Scope of Audit',
                    'Audit Strategy',
                    'Risk Assessment',
                    'Audit Evidence',
                    'Audit of Financial Statements',
                    'Audit Documentation',
                    'Completion and Review',
                    'Audit Report',
                    'Audit of Different Types of Entities',
                    'Audit of Banks',
                    'Ethics and Terms of Engagements',
                ],
            },
            {
                'name': 'Paper 6A - Financial Management',
                'code': 'P6A',
                'order': 7,
                'chapters': [
                    'Scope and Objectives of FM',
                    'Types of Financing',
                    'Ratio Analysis',
                    'Cost of Capital',
                    'Capital Structure',
                    'Leverages',
                    'Investment Decisions',
                    'Dividend Decisions',
                    'Management of Working Capital',
                ],
            },
            {
                'name': 'Paper 6B - Strategic Management',
                'code': 'P6B',
                'order': 8,
                'chapters': [
                    'Introduction to Strategic Management',
                    'External Environment',
                    'Internal Environment',
                    'Strategic Choices',
                    'Strategic Implementation and Evaluation',
                ],
            },
        ],
    },
    {
        'name': 'CA FINAL',
        'order': 3,
        'papers': [
            {
                'name': 'Paper 1 - Financial Reporting',
                'code': 'P1',
                'order': 1,
                'chapters': [
                    'Introduction to Ind AS',
                    'Framework for Financial Reporting',
                    'Ind AS 1', 'Ind AS 2', 'Ind AS 7', 'Ind AS 8', 'Ind AS 10',
                    'Ind AS 12', 'Ind AS 16', 'Ind AS 19', 'Ind AS 20', 'Ind AS 21',
                    'Ind AS 23', 'Ind AS 24', 'Ind AS 33', 'Ind AS 34', 'Ind AS 36',
                    'Ind AS 37', 'Ind AS 38', 'Ind AS 40', 'Ind AS 41',
                    'Ind AS 101', 'Ind AS 102', 'Ind AS 103', 'Ind AS 105', 'Ind AS 108',
                    'Financial Instruments',
                    'Consolidated Financial Statements',
                    'Fair Value Measurement',
                    'Revenue from Contracts',
                    'Leases',
                    'Analysis of Financial Statements',
                    'Professional Ethics',
                    'Accounting and Technology',
                ],
            },
            {
                'name': 'Paper 2 - Advanced Financial Management',
                'code': 'P2',
                'order': 2,
                'chapters': [
                    'Financial Policy',
                    'Risk Management',
                    'Capital Budgeting',
                    'Security Analysis',
                    'Portfolio Management',
                    'Securitization',
                    'Mutual Funds',
                    'Derivatives',
                    'Forex Risk Management',
                    'International Finance',
                    'Interest Rate Risk',
                    'Business Valuation',
                    'Mergers and Acquisitions',
                    'Startup Finance',
                ],
            },
            {
                'name': 'Paper 3 - Advanced Auditing',
                'code': 'P3',
                'order': 3,
                'chapters': [
                    'Quality Control',
                    'Auditors Responsibilities',
                    'Audit Planning',
                    'Materiality',
                    'Audit Evidence',
                    'Completion and Review',
                    'Reporting',
                    'Specialised Areas',
                    'Related Services',
                    'Review of Financial Information',
                    'Prospective Financial Information',
                    'Digital Auditing',
                    'Group Audits',
                    'Audit of Banks',
                    'Public Sector Audit',
                    'Internal Audit',
                    'Due Diligence',
                    'ESG Assurance',
                    'Professional Ethics',
                ],
            },
            {
                'name': 'Paper 4 - Direct Tax and International Taxation',
                'code': 'P4',
                'order': 4,
                'chapters': [
                    'Basic Concepts',
                    'Total Income',
                    'Business Income',
                    'Capital Gains',
                    'Other Sources',
                    'Clubbing of Income',
                    'Set Off and Carry Forward',
                    'Deductions',
                    'Assessment of Various Entities',
                    'Assessment Procedures',
                    'Appeals and Revision',
                    'Tax Planning',
                    'International Taxation',
                    'Transfer Pricing',
                    'Advance Rulings',
                    'BEPS',
                    'Model Tax Conventions',
                ],
            },
            {
                'name': 'Paper 5 - Indirect Tax Laws',
                'code': 'P5',
                'order': 5,
                'chapters': [
                    'Supply under GST',
                    'Charge of GST',
                    'Place of Supply',
                    'Exemptions from GST',
                    'Time of Supply',
                    'Value of Supply',
                    'Input Tax Credit',
                    'Registration',
                    'Tax Invoice',
                    'Accounts and Records',
                    'Payment of Tax',
                    'Electronic Commerce',
                    'Returns',
                    'Import and Export under GST',
                    'Refunds',
                    'Job Work',
                    'Assessment and Audit',
                    'Search and Seizure',
                    'Demands and Recovery',
                    'Advance Ruling',
                    'Customs Duty',
                    'Levy and Exemptions',
                    'Classification of Goods',
                    'Warehousing',
                    'Foreign Trade Policy',
                ],
            },
            {
                'name': 'Paper 6 - Integrated Business Solutions',
                'code': 'P6',
                'order': 6,
                'chapters': [
                    'Multi Subject Case Studies',
                    'Integrated Practical Questions',
                    'Strategic Integrated Problems',
                    'Real-world ICAI Case Studies',
                ],
            },
        ],
    },
]
