"""
Complete ICAI CA master structure — Levels → Papers → Chapters.
Topics are seeded per chapter in the management command (Theory, Practical, Exam Focus).
"""

DEFAULT_TOPICS = ['Theory & Concepts', 'Practical Problems', 'Exam Focus Questions']

ICAI_MASTER = [
    {
        'name': 'CA FOUNDATION',
        'order': 1,
        'papers': [
            {
                'name': 'Paper 1 - Accounting',
                'code': 'P1',
                'order': 1,
                'chapters': [
                    'Theoretical Framework',
                    'Accounting Process',
                    'Bank Reconciliation Statement',
                    'Inventories',
                    'Depreciation and Amortisation',
                    'Bill of Exchange and Promissory Notes',
                    'Preparation of Final Accounts of Sole Proprietors',
                    'Financial Statements of Not-for-Profit Organisations',
                    'Accounts for Incomplete Records',
                    'Partnership and LLP Accounts',
                    'Company Accounts',
                ],
            },
            {
                'name': 'Paper 2 - Business Laws',
                'code': 'P2',
                'order': 2,
                'chapters': [
                    'Indian Regulatory Framework',
                    'The Indian Contract Act 1872',
                    'The Sale of Goods Act 1930',
                    'The Indian Partnership Act 1932',
                    'The Limited Liability Partnership Act 2008',
                    'The Companies Act 2013',
                    'The Negotiable Instruments Act 1881',
                ],
            },
            {
                'name': 'Paper 3 - Quantitative Aptitude',
                'code': 'P3',
                'order': 3,
                'chapters': [
                    'Ratio and Proportion, Indices, Logarithms',
                    'Equations',
                    'Linear Inequalities',
                    'Mathematics of Finance',
                    'Basic Concepts of Permutations and Combinations',
                    'Sequence and Series',
                    'Sets, Relations and Functions',
                    'Limits and Continuity Functions',
                    'Differential and Integral Calculus',
                    'Number Series',
                    'Coding and Decoding',
                    'Odd Man Out',
                    'Direction Sense Test',
                    'Seating Arrangements',
                    'Blood Relations',
                    'Statistical Description of Data',
                    'Measures of Central Tendency',
                    'Probability',
                    'Theoretical Distributions',
                    'Correlation and Regression',
                    'Index Numbers',
                ],
            },
            {
                'name': 'Paper 4 - Economics',
                'code': 'P4',
                'order': 4,
                'chapters': [
                    'Nature and Scope of Business Economics',
                    'Theory of Demand and Supply',
                    'Theory of Production and Cost',
                    'Price Determination in Different Markets',
                    'Business Cycles',
                    'Determination of National Income',
                    'Public Finance',
                    'Money Market',
                ],
            },
        ],
    },
    {
        'name': 'CA INTERMEDIATE',
        'order': 2,
        'papers': [
            {
                'name': 'Paper 1 - Advanced Accounting',
                'code': 'P1',
                'order': 1,
                'chapters': [
                    'AS 1', 'AS 2', 'AS 3', 'AS 4', 'AS 5', 'AS 7', 'AS 9', 'AS 10',
                    'AS 11', 'AS 12', 'AS 13', 'AS 14', 'AS 15', 'AS 16', 'AS 17', 'AS 18',
                    'AS 19', 'AS 20', 'AS 21', 'AS 22', 'AS 23', 'AS 24', 'AS 25', 'AS 26',
                    'AS 27', 'AS 28', 'AS 29',
                    'Financial Statements of Companies',
                    'Buyback of securities',
                    'Amalgamation of Companies',
                    'Accounting For Reconstruction of Companies',
                    'Accounting for Branches Including Foreign Companies',
                    'Applicability of Accounting Standards',
                    'Introduction to Accounting Standards',
                ],
            },
            {
                'name': 'Paper 2 - Corporate and Other Laws',
                'code': 'P2',
                'order': 2,
                'chapters': [
                    'Preliminary',
                    'Incorporation of Company and Matters Incidental Thereto',
                    'Prospectus and Allotment of Securities',
                    'Share Capital and Debenturs',
                    'Acceptance of Deposits by Companies',
                    'Registration of Charges',
                    'Management and Administration',
                    'Declaration and Payment of Dividend',
                    'Accounts of Companies',
                    'Audit and Auditors',
                    'Companies Incorporated Outside India',
                    'The Limited Liability Partnership Act,2008',
                    'The General Clauses Act,1897',
                    'Interpretation of Statutes',
                    'The Foreign Exchange Management Act,1999',
                ],
            },
            {
                'name': 'Paper 3A - Direct Tax',
                'code': 'P3A',
                'order': 3,
                'chapters': [
                    'Basic Concepts',
                    'Residence and Scope of Total Income',
                    'Salaries',
                    'Income from House Property',
                    'Profits and Gains of Business and Profession',
                    'Capital Gains',
                    'Income from Other Source',
                    'Income of Other Persons included in Assessess\'s Total Income',
                    'Aggregation of Income,Set-Off and Carry Forward of Losses',
                    'Deductions from Gross Total Income',
                    'Advance Tax,Tax Deducted at Source and Tax Collection at Source',
                    'Income Tax Liability-Computation and Optimisation',
                ],
            },
            {
                'name': 'Paper 3B - Goods and Service Tax',
                'code': 'P3B',
                'order': 4,
                'chapters': [
                    'GST in India-An Introduction',
                    'Supply under GST',
                    'Charge of GST',
                    'Place of Supply',
                    'Supply under GST',
                    'Exemptions from GST',
                    'Time of Supply',
                    'Value of Supply',
                    'Input Tax Credit',
                    'Registration',
                    'Tax Invoice;Credit and Debit Notes',
                    'Accounts and Records',
                    'E-way Bill',
                    'Payment of Tax',
                    'Tax Deduction at Source and Collection of Tax at Source',
                    'Returns',
                ],
            },
            {
                'name': 'Paper 4 - Cost and Management Accounting',
                'code': 'P4',
                'order': 5,
                'chapters': [
                    'Introduction to Cost and Management Accounting',
                    'Material Cost',
                    'Employee Cost and Direct Expenses',
                    'Overheads - Absorption Costing Method',
                    'Activity Based Costing',
                    'Cost Sheet',
                    'Cost Accounting System',
                    'Unit & Batch Costing',
                    'Job Costing',
                    'Process & Operation Costing',
                    'Joint Products and By Products',
                    'Service Costing',
                    'Standard Costing',
                    'Marginal Costing',
                    'Budgets and Budgetary Control',
                ],
            },
            {
                'name': 'Paper 5 - Auditing and ethics',
                'code': 'P5',
                'order': 6,
                'chapters': [
                    'Nature, Objective and Scope of Audit',
                    'Audit Strategy,Audit Planning and Audit Programme',
                    'Risk Assessment and Internal Control',
                    'Audit Evidence',
                    'Audit of Items of Financial Statements',
                    'Audit Documentation',
                    'Completion and Review',
                    'Audit Report',
                    'Special Features of Audit of Different Type of Entities',
                    'Audit of Banks',
                    'Ethics and Terms of Audit Engagements',
                ],
            },
            {
                'name': 'Paper 6A - Financial Management',
                'code': 'P6A',
                'order': 7,
                'chapters': [
                    'Scope and Objectives of Financial Management',
                    'Types of Financing',
                    'Financial Analysis and Planning - Ratio Analysis',
                    'Cost of Capital',
                    'Financing Decisions - Capital Structure',
                    'Financing Decisions - Leverages',
                    'Investment Decisions',
                    'Dividend Decisions',
                    'Management of Working Capital',
                ],
            },
            {
                'name': 'Paper 6B - Strategic Management',
                'code': 'P6B',
                'order': 8,
                'chapters': [
                    'Introduction to Strategic Management',
                    'Strategic Analysis: External Environment',
                    'Strategic Analysis: Internal Environment',
                    'Strategic Choices',
                    'Strategic Implementation and Evaluation',
                ],
            },
        ],
    },
    {
        'name': 'CA FINAL',
        'order': 3,
        'papers': [
            {
                'name': 'Paper 1 - Financial Reporting',
                'code': 'P1',
                'order': 1,
                'chapters': [
                    'Introduction to Ind AS',
                    'Framework for Financial Reporting',
                    'Ind AS 1', 'Ind AS 2', 'Ind AS 7', 'Ind AS 8', 'Ind AS 10',
                    'Ind AS 12', 'Ind AS 16', 'Ind AS 19', 'Ind AS 20', 'Ind AS 21',
                    'Ind AS 23', 'Ind AS 24', 'Ind AS 33', 'Ind AS 34', 'Ind AS 36',
                    'Ind AS 37', 'Ind AS 38', 'Ind AS 40', 'Ind AS 41',
                    'Ind AS 101', 'Ind AS 102', 'Ind AS 103', 'Ind AS 105', 'Ind AS 108',
                    'Financial Instruments',
                    'Consolidated Financial Statements',
                    'Fair Value Measurement',
                    'Revenue from Contracts',
                    'Leases',
                    'Analysis of Financial Statements',
                    'Professional Ethics',
                    'Accounting and Technology',
                ],
            },
            {
                'name': 'Paper 2 - Advanced Financial Management',
                'code': 'P2',
                'order': 2,
                'chapters': [
                    'Financial Policy',
                    'Risk Management',
                    'Capital Budgeting',
                    'Security Analysis',
                    'Portfolio Management',
                    'Securitization',
                    'Mutual Funds',
                    'Derivatives',
                    'Forex Risk Management',
                    'International Finance',
                    'Interest Rate Risk',
                    'Business Valuation',
                    'Mergers and Acquisitions',
                    'Startup Finance',
                ],
            },
            {
                'name': 'Paper 3 - Advanced Auditing, Assurance and Professional ethics',
                'code': 'P3',
                'order': 3,
                'chapters': [
                    'Quality Control',
                    'Auditors Responsibilities',
                    'Audit Planning',
                    'Materiality',
                    'Audit Evidence',
                    'Completion and Review',
                    'Reporting',
                    'Specialised Areas',
                    'Related Services',
                    'Review of Financial Information',
                    'Prospective Financial Information',
                    'Digital Auditing',
                    'Group Audits',
                    'Audit of Banks',
                    'Public Sector Audit',
                    'Internal Audit',
                    'Due Diligence',
                    'ESG Assurance',
                    'Professional Ethics',
                ],
            },
            {
                'name': 'Paper 4 - Direct Tax and International Taxation',
                'code': 'P4',
                'order': 4,
                'chapters': [
                    'Basic Concepts',
                    'Total Income',
                    'Business Income',
                    'Capital Gains',
                    'Other Sources',
                    'Clubbing of Income',
                    'Set Off and Carry Forward',
                    'Deductions',
                    'Assessment of Various Entities',
                    'Assessment Procedures',
                    'Appeals and Revision',
                    'Tax Planning',
                    'International Taxation',
                    'Transfer Pricing',
                    'Advance Rulings',
                    'BEPS',
                    'Model Tax Conventions',
                ],
            },
            {
                'name': 'Paper 5 - Indirect Tax Laws',
                'code': 'P5',
                'order': 5,
                'chapters': [
                    'Supply under GST',
                    'Charge of GST',
                    'Place of Supply',
                    'Exemptions from GST',
                    'Time of Supply',
                    'Value of Supply',
                    'Input Tax Credit',
                    'Registration',
                    'Tax Invoice',
                    'Accounts and Records',
                    'Payment of Tax',
                    'Electronic Commerce',
                    'Returns',
                    'Import and Export under GST',
                    'Refunds',
                    'Job Work',
                    'Assessment and Audit',
                    'Search and Seizure',
                    'Demands and Recovery',
                    'Advance Ruling',
                    'Customs Duty',
                    'Levy and Exemptions',
                    'Classification of Goods',
                    'Warehousing',
                    'Foreign Trade Policy',
                ],
            },
            {
                'name': 'Paper 6 - Integrated Business Solutions',
                'code': 'P6',
                'order': 6,
                'chapters': [
                    'Multi Subject Case Studies',
                    'Integrated Practical Questions',
                    'Strategic Integrated Problems',
                    'Real-world ICAI Case Studies',
                ],
            },
        ],
    },
]
