# Generated by Django 6.0.5 on 2026-05-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_level_options_alter_subtopic_options_and_more'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('q_no', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('has_notes', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subtopic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjective_questions', to='courses.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjective_questions', to='courses.topic')),
            ],
            options={
                'ordering': ['-year', 'q_no'],
            },
        ),
    ]
