# Generated by Django 6.0.5 on 2026-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpaper',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/pdfs/'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/pdfs/'),
        ),
        migrations.AddField(
            model_name='notes',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/pdfs/'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/pdfs/'),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/pdfs/'),
        ),
        migrations.AddField(
            model_name='video',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/pdfs/'),
        ),
        migrations.AlterField(
            model_name='answerpaper',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
