# Generated by Django 6.0.2 on 2026-05-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_answerpaper_pdf_file_mcq_pdf_file_notes_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectivequestion',
            name='attempt',
            field=models.CharField(blank=True, choices=[('JAN', 'January'), ('MAY', 'May'), ('SEP', 'September'), ('NOV', 'November')], max_length=10),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='question_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('NORMAL', 'Normal Question')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D')], max_length=1),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('ARCHIVED', 'Archived'), ('PUBLISHED', 'Published')], default='ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='marks',
            field=models.IntegerField(choices=[(1, '1 Mark'), (2, '2 Marks'), (4, '4 Marks'), (5, '5 Marks'), (8, '8 Marks'), (10, '10 Marks'), (12, '12 Marks'), (16, '16 Marks')]),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='source',
            field=models.CharField(choices=[('MTP-01', 'MTP-01'), ('MTP-02', 'MTP-02'), ('RTP', 'RTP'), ('Suggested Answers', 'Suggested Answers'), ('Model Test Paper 1', 'Model Test Paper 1'), ('Model Test Paper 2', 'Model Test Paper 2'), ('Model Test Paper 3', 'Model Test Paper 3'), ('Model Test Paper 4', 'Model Test Paper 4'), ('Model Test Paper 5', 'Model Test Paper 5'), ('Model Test Paper 6', 'Model Test Paper 6'), ('Model Test Paper 7', 'Model Test Paper 7'), ('Model Test Paper 8', 'Model Test Paper 8'), ('Other', 'Other')], max_length=100),
        ),
    ]
