# Generated by Django 6.0.2 on 2026-05-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_subjectivequestion_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectivequestion',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
