# Generated by Django 6.0.2 on 2026-05-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_subjectivequestion_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectivequestion',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='mcq_correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='table_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
