# Generated by Django 6.0.2 on 2026-05-25 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_subjectivequestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=5)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('NORMAL', 'Normal Question')], default='NORMAL', max_length=10)),
                ('option_a', models.CharField(blank=True, max_length=500, null=True)),
                ('option_b', models.CharField(blank=True, max_length=500, null=True)),
                ('option_c', models.CharField(blank=True, max_length=500, null=True)),
                ('option_d', models.CharField(blank=True, max_length=500, null=True)),
                ('mcq_correct_option', models.CharField(blank=True, max_length=1, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('table_data', models.TextField(blank=True, null=True)),
                ('marks', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='materials.subjectivequestion')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
    ]
