# Generated by Django 6.0.2 on 2026-05-25 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_level_options_alter_subtopic_options_and_more'),
        ('materials', '0008_subquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectivequestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='has_notes',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='mcq_correct_option',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='mcq_correct_option',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='option_d',
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='attempt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='difficulty',
            field=models.CharField(default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='marks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='q_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjective_questions', to='courses.subtopic'),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjective_questions', to='courses.topic'),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='question_type',
            field=models.CharField(choices=[('NORMAL', 'Theory'), ('MCQ', 'MCQ')], default='NORMAL', max_length=10),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='materials.subjectivequestion')),
                ('sub_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='materials.subquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
