# Generated by Django 6.0.5 on 2026-05-25 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_level_options_alter_subtopic_options_and_more'),
        ('master_data', '0001_initial'),
        ('materials', '0009_alter_subjectivequestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectivequestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='answer_table_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='formula_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='icai_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='master_data.icaitopic'),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='answer_table_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='formula_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='attempt',
            field=models.CharField(default='MAY', max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='q_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='question_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('NORMAL', 'Normal Question'), ('MIXED', 'Mixed Question'), ('THEORY', 'Theory Question')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('ARCHIVED', 'Archived'), ('PUBLISHED', 'Published')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjective_questions', to='courses.subtopic'),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjective_questions', to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='identifier',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
