# Generated by Django 6.0.5 on 2026-06-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_alter_subjectivequestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectivequestion',
            options={'ordering': ['topic__order', 'id']},
        ),
    ]
