# Generated by Django 6.0.5 on 2026-06-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_add_case_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectivequestion',
            name='case_scenario_passage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('NORMAL', 'Normal Question'), ('MIXED', 'Mixed Question'), ('THEORY', 'Theory Question'), ('CASE_SCENARIO', 'Case Scenario')], default='NORMAL', max_length=15),
        ),
    ]
