# Generated by Django 6.0.5 on 2026-06-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_level_options_alter_subtopic_options_and_more'),
        ('master_data', '0001_initial'),
        ('materials', '0013_alter_subjectivequestion_case_scenario_passage_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subjectivequestion',
            index=models.Index(fields=['status'], name='question_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectivequestion',
            index=models.Index(fields=['difficulty'], name='question_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectivequestion',
            index=models.Index(fields=['question_type'], name='question_type_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectivequestion',
            index=models.Index(fields=['icai_topic'], name='question_icai_topic_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectivequestion',
            index=models.Index(fields=['topic'], name='question_topic_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectivequestion',
            index=models.Index(fields=['subject'], name='question_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectivequestion',
            index=models.Index(fields=['created_at'], name='question_created_at_idx'),
        ),
    ]
