# Generated by Django 6.0.5 on 2026-06-16 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_calevel_qualification'),
        ('materials', '0016_subjectivequestion_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectivequestion',
            name='icai_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='master_data.icaitopic'),
        ),
    ]
