# Generated by Django 6.0.5 on 2026-06-16 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_alter_subjectivequestion_icai_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectivequestion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='related_concept',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('PRACTICE', 'Practice Session'), ('MOCK', 'Mock Test')], default='PRACTICE', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('course_level', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('chapter', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('total_questions', models.IntegerField(default=10)),
                ('difficulty', models.CharField(default='MIXED', max_length=20)),
                ('mode', models.CharField(default='LEARNING', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_answer', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('score_obtained', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.subjectivequestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.questionoption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='materials.assessmentsession')),
            ],
        ),
    ]
