# Generated by Django 6.0.5 on 2026-06-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_subjectivequestion_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('qualification', models.CharField(max_length=100)),
                ('course_level', models.CharField(blank=True, default='', max_length=100)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('total_questions', models.IntegerField(default=50)),
                ('difficulty', models.CharField(default='MIXED', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='mock_templates', to='materials.subjectivequestion')),
            ],
        ),
    ]
