# Generated by Django 6.0.5 on 2026-06-18 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_studentprogress_status'),
        ('materials', '0020_alter_liveclass_course_alter_liveclass_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.level'),
        ),
    ]
