# Generated by Django 6.0.5 on 2026-06-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_liveclass_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
