# Generated by Django 6.0.5 on 2026-06-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_liveclass_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectivequestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('NONE', 'No Mention')], default='MEDIUM', max_length=20),
        ),
    ]
