# Generated by Django 6.0.5 on 2026-09-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_alter_subjectivequestion_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectivequestion',
            name='ec2_question_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='model_source_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='source_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
